CREATE TABLE IF NOT EXISTS Genre (
		Id SERIAL PRIMARY KEY,
		Title VARCHAR(40) NOT NULL
);
	

CREATE TABLE IF NOT EXISTS Executor (
		Id SERIAL PRIMARY KEY,
		Name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS GenreExecutor (
		Genre_id INTEGER REFERENCES Genre(Id),
		Executor_id INTEGER REFERENCES Executor(Id),
		CONSTRAINT pk PRIMARY KEY (Genre_id, Executor_id)
);


CREATE TABLE IF NOT EXISTS Album (
		Id SERIAL PRIMARY KEY,
		Name VARCHAR(40) NOT NULL,
		Year_of_release date NOT NULL 
);

CREATE TABLE IF NOT EXISTS ExecutorAlbum (
		Id SERIAL PRIMARY KEY,
		Executor_id INTEGER NOT NULL REFERENCES Executor(Id),
		Album_id INTEGER NOT NULL REFERENCES Album(Id)
);

CREATE TABLE IF NOT EXISTS Track (
		Id SERIAL PRIMARY KEY,
		Title VARCHAR(40) NOT NULL,
		Duration numeric,
		Album_id INTEGER NOT NULL REFERENCES Album(Id)
);

CREATE TABLE IF NOT EXISTS Comparation (
		Id SERIAL PRIMARY KEY,
		Title VARCHAR(40) NOT NULL,
		year_of_issue date NOT NULL
);

CREATE TABLE IF NOT EXISTS ComparationTrack (
		Id SERIAL PRIMARY KEY,
		Comparation_id INTEGER NOT NULL REFERENCES Comparation(Id),
		Track_id INTEGER NOT NULL REFERENCES Track(Id)
);

